/**
 * This script generates `src/p-uni.ts` from types declared in `src/filters.ts`.
 *
 * What it does:
 * - Loads the TypeScript project via ts-morph (using tsconfig.json).
 * - Reads the `PromisifiableFunctionNames` type alias (a union of string literal names)
 *   to determine which Uni API functions should be wrapped with `promisify`.
 * - Reads the `Uni` type alias to iterate all API properties (methods).
 * - For each property, preserves its JSDoc and either:
 *   - exports `promisify(uni.prop)` when the property name is included in
 *     PromisifiableFunctionNames, or
 *   - exports `uni.prop` directly when it is not promisifiable.
 * - Formats the generated file with Prettier and writes it to `src/p-uni.ts`.
 */

import { outputFile } from 'fs-extra'
import { format } from 'prettier'
import { Project, SyntaxKind } from 'ts-morph'

const project = new Project({
  tsConfigFilePath: 'tsconfig.json',
})

const filtersSourceFile = project.getSourceFileOrThrow('src/filters.ts')
const typeChecker = project.getTypeChecker()

// Get the type that lists names of functions we should promisify.
const promisifiableFunctionNamesType = typeChecker.getTypeAtLocation(
  filtersSourceFile.getTypeAliasOrThrow('PromisifiableFunctionNames').getNameNode()
)!

// The type is a union of string literal types — extract each literal.
const promisifiableUnionTypes = promisifiableFunctionNamesType.getUnionTypes()

const promisifiableNames = promisifiableUnionTypes.map((t) => {
  const text = typeChecker.getTypeText(t)
  return text.replace(/^['"]/g, '').replace(/['"]$/g, '')
})

promisifiableNames.sort()

const uniTypeAlias = filtersSourceFile.getTypeAliasOrThrow('Uni')
const uniType = typeChecker.getTypeAtLocation(uniTypeAlias.getNameNode())!
const uniProperties = uniType.getProperties()

const outputLines: string[] = [
  '// This file is auto generated by `uniapp-promisify`. Do not edit it manually.',
  '',
  "import { promisify } from './index'",
]

uniProperties.forEach((property) => {
  const propName = property.getName()
  const matchedPromisifiableName = promisifiableNames.find((n) => propName === n)

  const valueDecl = property.getValueDeclarationOrThrow()
  const methodSignature = valueDecl.asKindOrThrow(SyntaxKind.MethodSignature)

  // Preserve JSDoc for the property/method
  methodSignature.getJsDocs().forEach((doc) => {
    outputLines.push(doc.getText().trim())
  })

  if (matchedPromisifiableName) {
    outputLines.push(`export const ${propName} = promisify(uni.${propName})`)
  } else {
    outputLines.push(`export const ${propName} = uni.${propName}`)
  }
  outputLines.push('')
})

format(outputLines.join('\n'), {
  parser: 'typescript',
  singleQuote: true,
  trailingComma: 'all',
  semi: false,
  useTabs: false,
  tabWidth: 2,
  printWidth: 1000, // avoid line breaks
}).then((formatted) => {
  const path = 'src/p-uni.ts'
  outputFile(path, formatted)
})
